name: Rumput

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 */6 * * *"

jobs:
  rumput:
    runs-on: ubuntu-latest
    steps:
      - name : global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "fajarriiann@gmail.com"
          git config --local user.name "fajarriiann"
          git add -A

          arr[0]="berkata: kamu nanya?"
          arr[1]="berkata: kamu bertanya - tanya"
          arr[2]="berkata: yaudah"
          arr[3]="berkata: aku kasih tau ya"
          arr[4]="berkata: tapi boong!"
          arr[5]="berkata: blokkk!"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"

      - name: Github Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
